service: chinook-RestAPI

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 2048
  stage: dev
  timeout: 30
  region: ap-south-1
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello
    events:
      - http: ANY /{proxy+}
      - http: ANY /
    # environment: 
    #   USERNAME: ${{ secret.USERNAME }}
    #   PASSWORD: ${{ secret.PASSWORD }}
    #   HOSTNAME: ${{ secret.HOSTNAME }} 
    #   PORT:  ${{ secret.PORT }} 
    #   DATABASE: ${{ secret.DATABASE }} 

plugins:
  - serverless-offline